### ISSUE TITLE
Add Travis Support to test minimal different php version

### ISSUE THREAD

**Issue by bueltge** [pluginkollektiv/statify#50]
- test different php version
- phpcs validation, needs Composer Support

`.travis.yml`

```
language: php

services:
  - mysql

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - mysql -e 'CREATE DATABASE test__database;'


before_script:
  - composer install --no-progress --prefer-source

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs ./inc/ --standard=phpcs.ruleset.xml --extensions=php
```

`composer.json`

```
{
	"name": "pluginkollektiv/statify",
	"description": "Compact, easy-to-use and privacy-compliant stats plugin for WordPress.",
	"keywords": [
		"wordpress",
		"plugin",
		"statistics"
	],
	"license": "GPL-3.0+",
	"type": "wordpress-plugin",
	"homepage": "https://github.com/pluginkollektiv/statify/",
	"support": {
		"issues": "https://github.com/pluginkollektiv/statify/issues"
	},
	"require": {
		"php": ">=5.4",
		"composer/installers": "~1.0"
	},
	"require-dev": {
		"php": ">=5.4",
		"wp-coding-standards/wpcs": "~0.6.0"
	},
	"scripts": {
		"post-install-cmd": [
			"@phpcs"
		],
		"post-update-cmd": [
			"@phpcs"
		],
		"phpcs": "\"vendor/bin/phpcs\" --config-set installed_paths vendor/wp-coding-standards/wpcs"
	}
}
```

`phpcs.ruleset.xml`
I'm use the follow enhancement - https://github.com/inpsyde/Codex/tree/master/tools/CodeSniffer
